SET ECHO ON

BREAK ON DeptNo SKIP 1
COMPUTE SUM OF MonRate ON DeptNo

SELECT DeptNo, LName, FName, MonRate
FROM Employees
ORDER BY DeptNo, LName, FName;

BREAK ON DeptNo SKIP 1 ON REPORT
COMPUTE SUM OF MonRate ON DeptNo REPORT
COLUMN MonRate FORMAT $9,999,990.00

SELECT DeptNo, LName, FName, MonRate
FROM Employees
ORDER BY DeptNo, LName, FName;

BREAK ON DeptNo SKIP 1 ON REPORT
COMPUTE SUM LABEL 'Department Total:' OF MonRate ON DeptNo
COMPUTE SUM LABEL 'Corporate Total:' OF MonRate ON REPORT
COLUMN MonRate FORMAT $9,999,990.00
COLUMN DeptNo HEADING 'DEPARTMENT ' FORMAT 9999999999999999999999

SELECT DeptNo, LName, FName, MonRate
FROM Employees
ORDER BY DeptNo, LName, FName;


CLEAR BREAK
CLEAR COMPUTES
CLEAR COLUMNS
@Login

SET ECHO OFF
