--SET ECHO ON

BREAK ON DeptNo SKIP 
COLUMN The_Date NOPRINT NEW_VALUE Date_Today
select to_char(sysdate ,'fmMonth fmdd, YYYY HH:mi:ss AM') The_date from dual;
TTITLE CENTER 'Company Employee Report' SKIP SKIP -
  LEFT 'Created By: ' SQL.USER   RIGHT Date_Today SKIP SKIP
BTITLE CENTER '****************END OF REPORT*************'
COMPUTE SUM OF SAL ON DeptNo


SELECT DeptNo, EName, SAL
FROM Emp
ORDER BY DeptNo, EName;

BREAK ON DeptNo SKIP 1 ON REPORT
COMPUTE SUM OF SAL ON DeptNo REPORT
COLUMN SAL FORMAT $9,999,990.00

SELECT DeptNo, EName, SAL
FROM Emp
ORDER BY DeptNo, EName;

BREAK ON DeptNo SKIP 1 ON REPORT
COMPUTE SUM LABEL 'Department Total:' OF SAL ON DeptNo
COMPUTE SUM LABEL 'Corporate Total:' OF SAL ON REPORT
COLUMN MonRate FORMAT $9,999,990.00
COLUMN DeptNo HEADING 'DEPARTMENT ' FORMAT 9999999999999999999999

SELECT DeptNo, EName, SAL
FROM Emp
ORDER BY DeptNo, EName;


CLEAR BREAK
CLEAR COMPUTES
CLEAR COLUMNS


SET ECHO OFF
