SET DEFINE OFF;
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (10, 'Greg', 13500, TO_DATE('7/1/2012', 'MM/DD/YYYY'));
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (20, 'Matt', 800, TO_DATE('7/1/2012', 'MM/DD/YYYY'));
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (10, 'Greg', 12500, TO_DATE('7/1/2012', 'MM/DD/YYYY'));
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (20, 'Matt', 9000, TO_DATE('6/1/2012', 'MM/DD/YYYY'));
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (30, 'Greg', 7000, TO_DATE('5/1/2012', 'MM/DD/YYYY'));
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (40, 'Greg', 3500, TO_DATE('4/1/2012', 'MM/DD/YYYY'));
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (50, 'Jeff', 11000, TO_DATE('3/1/2012', 'MM/DD/YYYY'));
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (60, 'Stan', 11500, TO_DATE('2/1/2012', 'MM/DD/YYYY'));
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (10, 'Greg', 12500, TO_DATE('4/1/2012', 'MM/DD/YYYY'));
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (40, 'Jeff', 1250, TO_DATE('4/1/2012', 'MM/DD/YYYY'));
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (10, 'Kevin', 12500, TO_DATE('7/1/2012', 'MM/DD/YYYY'));
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (20, 'Jeff', 800, TO_DATE('7/1/2012', 'MM/DD/YYYY'));
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (10, 'Greg', 15000, TO_DATE('7/1/2012', 'MM/DD/YYYY'));
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (20, 'Jeff', 5500, TO_DATE('6/1/2012', 'MM/DD/YYYY'));
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (30, 'Greg', 8000, TO_DATE('5/1/2012', 'MM/DD/YYYY'));
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (40, 'Greg', 1500, TO_DATE('4/1/2012', 'MM/DD/YYYY'));
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (50, 'Matt', 12000, TO_DATE('3/1/2012', 'MM/DD/YYYY'));
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (60, 'Greg', 6000, TO_DATE('2/1/2012', 'MM/DD/YYYY'));
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (10, 'Matt', 10500, TO_DATE('4/1/2012', 'MM/DD/YYYY'));
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (40, 'Jeff', 1500, TO_DATE('4/1/2012', 'MM/DD/YYYY'));
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (10, 'Greg', 10000, TO_DATE('7/1/2012', 'MM/DD/YYYY'));
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (20, 'Jeff', 1250, TO_DATE('7/1/2012', 'MM/DD/YYYY'));
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (10, 'Greg', 15550, TO_DATE('7/1/2012', 'MM/DD/YYYY'));
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (20, 'Jeff', 4000, TO_DATE('6/1/2012', 'MM/DD/YYYY'));
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (30, 'Greg', 9000, TO_DATE('5/1/2012', 'MM/DD/YYYY'));
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (40, 'Greg', 3000, TO_DATE('4/1/2012', 'MM/DD/YYYY'));
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (50, 'Jeff', 8000, TO_DATE('3/1/2012', 'MM/DD/YYYY'));
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (60, 'Greg', 10500, TO_DATE('2/1/2012', 'MM/DD/YYYY'));
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (10, 'Greg', 10250, TO_DATE('4/1/2012', 'MM/DD/YYYY'));
Insert into STUDENT.COMPANY_SALES
   (CUST_ID, SALES_NAME, SALES_AMOUNT, SALES_DATE)
 Values
   (40, 'Jeff', 2000, TO_DATE('4/1/2012', 'MM/DD/YYYY'));
COMMIT;
