ALTER TABLE STUDENT.B
 DROP PRIMARY KEY CASCADE;

DROP TABLE STUDENT.B CASCADE CONSTRAINTS;

CREATE TABLE STUDENT.B
(
  ID      NUMBER,
  STATUS  CHAR(4 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX STUDENT.B_STATUS_IDX ON STUDENT.B
(STATUS)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX STUDENT.PK_B_ID ON STUDENT.B
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE STUDENT.B ADD (
  CONSTRAINT PK_B_ID
  PRIMARY KEY
  (ID)
  USING INDEX STUDENT.PK_B_ID
  ENABLE VALIDATE);
