DROP TABLE STUDENT.COMPANY_CUSTOMERS CASCADE CONSTRAINTS;

CREATE TABLE STUDENT.COMPANY_CUSTOMERS
(
  CUST_ID    NUMBER,
  CUST_NAME  VARCHAR2(10 BYTE),
  CUST_CITY  VARCHAR2(10 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
