ALTER TABLE STUDENT.EMP
 DROP PRIMARY KEY CASCADE;

DROP TABLE STUDENT.EMP CASCADE CONSTRAINTS;

CREATE TABLE STUDENT.EMP
(
  EMPNO     NUMBER(4)                           NOT NULL,
  ENAME     VARCHAR2(10 BYTE),
  JOB       VARCHAR2(9 BYTE),
  MGR       NUMBER(4),
  HIREDATE  DATE,
  SAL       NUMBER(7,2),
  COMM      NUMBER(7,2),
  DEPTNO    NUMBER(2)                           NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX STUDENT.EMP_PRIMARY_KEY ON STUDENT.EMP
(EMPNO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE STUDENT.EMP ADD (
  CONSTRAINT EMP_PRIMARY_KEY
  PRIMARY KEY
  (EMPNO)
  USING INDEX STUDENT.EMP_PRIMARY_KEY
  ENABLE VALIDATE);

ALTER TABLE STUDENT.EMP ADD (
  CONSTRAINT EMP_FOREIGN_KEY 
  FOREIGN KEY (DEPTNO) 
  REFERENCES STUDENT.DEPT (DEPTNO)
  ENABLE VALIDATE);
