ALTER TABLE STUDENT.PLSQL_PROFILER_UNITS
 DROP PRIMARY KEY CASCADE;

DROP TABLE STUDENT.PLSQL_PROFILER_UNITS CASCADE CONSTRAINTS;

CREATE TABLE STUDENT.PLSQL_PROFILER_UNITS
(
  RUNID           NUMBER,
  UNIT_NUMBER     NUMBER,
  UNIT_TYPE       VARCHAR2(32 BYTE),
  UNIT_OWNER      VARCHAR2(32 BYTE),
  UNIT_NAME       VARCHAR2(32 BYTE),
  UNIT_TIMESTAMP  DATE,
  TOTAL_TIME      NUMBER                        DEFAULT 0                     NOT NULL,
  SPARE1          NUMBER,
  SPARE2          NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE STUDENT.PLSQL_PROFILER_UNITS IS 'Information about each library unit in a run';


--  There is no statement for index STUDENT.SYS_C0011058.
--  The object is created when the parent object is created.

ALTER TABLE STUDENT.PLSQL_PROFILER_UNITS ADD (
  PRIMARY KEY
  (RUNID, UNIT_NUMBER)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE STUDENT.PLSQL_PROFILER_UNITS ADD (
  FOREIGN KEY (RUNID) 
  REFERENCES STUDENT.PLSQL_PROFILER_RUNS (RUNID)
  ON DELETE CASCADE
  ENABLE VALIDATE);
