DROP TABLE STUDENT.SALGRADE CASCADE CONSTRAINTS;

CREATE TABLE STUDENT.SALGRADE
(
  GRADE  NUMBER,
  LOSAL  NUMBER,
  HISAL  NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
